author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: URL to track bugs
repository:
  type: http
  url: URL
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
mainJob: ''
license: Apache 2.0
version: '20170321'
dependencies:
  openaf: '>=20170309'
files:
  - .package.yaml
  - LICENSE
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobHBS.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobTest.yaml
  - README.md
filesHash:
  .package.yaml: c9b58ae6aa629369fed128967d62135eae380850
  LICENSE: ff426822972c8972e3e4e782baac6f5304fd458c
  oJobBasics.yaml: 9ad331248d25969a8378249ec47e7672e837c040
  oJobDebug.yaml: 705a2a7b7f0a82aec514450903348d79692339cc
  oJobHBS.yaml: 60e6e6b765d913953fe8e421821b570b7d3cddb8
  oJobRest.yaml: 29c114576ce9ebf3a83b0a3bba9b7e7a7b29b88c
  oJobs.yaml: 1b5ac59fb16b34cbae0ae5ba5589e1b93bfbde99
  oJobSQL.yaml: 0baac5444973e263de74be27494f75acd66dab62
  oJobSSH.yaml: f19beddc554c0b7d5ca27ad9144bfa5ff5fc6a21
  oJobTest.yaml: 2be740a957fe3474861910c544f6345b64b06382
  README.md: de73d008f4e91bdd79afa859a00f6a3484129cb0
