author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: 'https://github.com/nmaguiar/oJob-common'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/nmaguiar/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
mainJob: ''
license: Apache 2.0
version: '20170811'
dependencies:
  openaf: '>=20170309'
files:
  - .package.yaml
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobHBS.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobSVN.yaml
  - oJobTest.yaml
filesHash:
  .package.yaml: b47dcade008076655a60cd24aecb784b941fc7cf
  oJobBasics.yaml: d94c9f5e4df71100110d314f63e4944eea7652ad
  oJobDebug.yaml: 32c8c37b82cb9741cb34ffc1118b5df4498a63d7
  oJobHBS.yaml: 56f2d5cb76a157adc450c49f0cb0b4e5ae7ff8a8
  oJobRest.yaml: 69de46a614d8382b3702aa0ee8ec484b36bc2e3c
  oJobs.yaml: 26b881af6d2a0c36e26e3d428781cdde54e4ae23
  oJobSQL.yaml: 0974b81f2b253b9c68897d611820e5b60b632a18
  oJobSSH.yaml: 1dce0acada74ca40d61df40ec37f2e62a2d39c25
  oJobSVN.yaml: c6dd797079a5fe01bfd92dbe4682ac0ebfb115c4
  oJobTest.yaml: fd77c30ea466b18c326d1428993eb80146ee6efd
