author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: URL to track bugs
repository:
  type: http
  url: URL
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
license: Apache 2.0
version: '20170321'
dependencies:
  openaf: '>=20170309'
files:
  - oJobs.yaml
  - oJobRest.yaml
  - oJobBasics.yaml
  - oJobSSH.yaml
  - oJobDebug.yaml
  - LICENSE
  - .package.yaml
  - oJobHBS.yaml
  - oJobTest.yaml
  - README.md
filesHash:
  oJobs.yaml: 6427479589a15784382a86eedef8a6d3cb3182cd
  oJobRest.yaml: 648c3e6e385b49218cb6c6479c1b1cfd43d66e3d
  oJobBasics.yaml: 1addaeb99679f8b63f0a1236752bfbb3d033e64e
  oJobSSH.yaml: 9f4250d8e67fc63b11e51ecdd7d1998c00caa4f7
  oJobDebug.yaml: fd432680ca91620fb2e0d584f30bd6b3e78d1ae8
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  .package.yaml: 0da670e08a8f83639a94a21dc5ecd4ce930b005a
  oJobHBS.yaml: 317e37b525a714012534f34bceed6d77ca44b04a
  oJobTest.yaml: 73be2e0f2fe5d4263c4d9b26099e9f3da2da9d13
  README.md: 626497dd1e492c621be6fa973a56373290708a2b
