author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - ojob
  - common
  - SQL
  - SSH
  - SVN
  - Test
  - Debug
  - HBS
  - Basics
  - Rest
bugs:
  url: 'https://github.com/OpenAF/oJob-common/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-common
main: ''
mainJob: ''
license: Apache 2.0
version: '20170811'
dependencies:
  openaf: '>=20170309'
files:
  - oJobBasics.yaml
  - LICENSE
  - oJobRest.yaml
  - oJobSVN.yaml
  - oJobHBS.yaml
  - oJobDebug.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - .package.yaml
  - README.md
  - oJobTest.yaml
  - oJobSSH.yaml
filesHash:
  oJobBasics.yaml: e67a906655a4bf1b315de07360f8449449efd187
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  oJobRest.yaml: e1a5f8d1809fffe51c285179f377f76300399eb0
  oJobSVN.yaml: bf6942c5e78ff1a3b6422fdcb6d3f0a7796ed467
  oJobHBS.yaml: ca018d16fcbdf3a9fc7450cab0d0325eed5e127f
  oJobDebug.yaml: e48ee42df640aba62925d513aad6a4831d924cd9
  oJobs.yaml: b6fa547806a46b5551cc96b06f2d6ff63ba1f16c
  oJobSQL.yaml: e491518238ffddb798fdad756dbdfafd2495d8f0
  README.md: 626497dd1e492c621be6fa973a56373290708a2b
  oJobTest.yaml: 9efaecac15234ef65b22d25a8fc990cd678e4470
  oJobSSH.yaml: 61927c6d08212c187fe60f78555b2b14c7b9cd72
