author: nmaguiar@gmail.com 
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf 
  - ojob 
bugs:
  url: URL to track bugs
repository:
  type: http
  url: URL
description: A set of base oJobs as common building blocks for custom oJobs. 
name: oJob-commons 
main: ''
license: Apache 2.0 
version: '20170308'
dependencies:
  openaf: '>=20170309'
files:
  - LICENSE
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobs.yaml
  - oJobSSH.yaml
  - oJobTest.yaml
  - README.md
  - .package.yaml
filesHash:
  LICENSE: ff426822972c8972e3e4e782baac6f5304fd458c
  oJobBasics.yaml: 9ad331248d25969a8378249ec47e7672e837c040
  oJobDebug.yaml: 705a2a7b7f0a82aec514450903348d79692339cc
  oJobs.yaml: a4a2616042cadef5e7b3b9b166503c09a3dd2370
  oJobSSH.yaml: 3c7e7eddd186c92e14e6b8d3b6b51d415256e501
  oJobTest.yaml: fb971e84600addd664b55ea43955cfa3895629c5
  README.md: de73d008f4e91bdd79afa859a00f6a3484129cb0
