author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - ojob
  - common
  - SQL
  - SSH
  - SVN
  - GIT
  - Test
  - Net
  - Debug
  - HBS
  - Basics
  - HTTPd
  - Rest
  - ES
  - ElasticSearch
  - WatchDog
  - Email
bugs:
  url: 'https://github.com/OpenAF/oJob-common/issues'
repository:
  type: http
  backurl: 'https://raw.githubusercontent.com/OpenAF/oJob-common/master'
  url: 'https://openaf.io/opacks/oJob-common.opack'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-common
main: ''
mainJob: ''
license: Apache 2.0
version: '20200526'
dependencies:
  openaf: '>=20200202'
files:
  - .package.yaml
  - LICENSE
  - oJobBasics.yaml
  - oJobCh.yaml
  - oJobDebug.yaml
  - oJobDirector.yaml
  - oJobEmail.yaml
  - oJobES.yaml
  - oJobGIT.yaml
  - oJobHBS.yaml
  - oJobHTTPd.yaml
  - oJobIO.yaml
  - oJobManager.yaml
  - oJobNet.yaml
  - oJobOPack.yaml
  - oJobRAID.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobSVN.yaml
  - oJobTest.yaml
  - oJobWatchDog.yaml
  - oJobXLS.yaml
  - README.md
filesHash:
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  oJobBasics.yaml: 8665bd587c927a891795fe20b6958f8e3af3542c
  oJobCh.yaml: 5f21cc46f4200b5f692bf4034fb4af22c2d7e6fb
  oJobDebug.yaml: 556cf30c9b6108fe9e9228a470a43039b7550a1c
  oJobDirector.yaml: 30009ded4b9c56fa1bbdda04f4d23d2db33c1151
  oJobEmail.yaml: 366597e3f42975ed432a5f02b05463fe90415f3b
  oJobES.yaml: 0d5e7ba5181f3344490aab6c42466c9189986812
  oJobGIT.yaml: 041aa8c4b393d2285a6b765e1ad5d76f59e2f10f
  oJobHBS.yaml: f314f109494e64e5ef5b24483a96ec59d54d6c11
  oJobHTTPd.yaml: 3d4fabcf5d96cc67f9cd4112b3f475af6c50873a
  oJobIO.yaml: 117a48b6c73a32b906dd05f9f085b37c4013ed92
  oJobManager.yaml: 52a7bd5e45edd98066ab34d53f9865fe59fc79ba
  oJobNet.yaml: a744fb83a9430ca9e34356bede5b0df8f2d48367
  oJobOPack.yaml: cd9542c6720f38758af1512060be295a8e608184
  oJobRAID.yaml: b4916cff81119a9e626c735abd6426964cdfc17c
  oJobRest.yaml: b312646597109a8b8e9b5dfda3f5d596b978bfd0
  oJobs.yaml: 83d8406c43b4a5325686467ed80911a9c1e26d49
  oJobSQL.yaml: e9adfe77c95fc0cf35478c23f5b21bc09dd63e57
  oJobSSH.yaml: 3f98d7d621f55abdfb933edc2c40f52405de94bd
  oJobSVN.yaml: ecfed00a4fa11b50ebf601168ac1251f7de29bfa
  oJobTest.yaml: 684560356b6e60c85c7230dd90c69c78fdd649f5
  oJobWatchDog.yaml: bf97b814e70dc86f585da1fbaf11072bf8a20657
  oJobXLS.yaml: 97c309095e07e0b7d86c6f1cb9fb383ddf204e6d
  README.md: 0d4aefad9c07910b18a5ee36c564888aab82ac29
