author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - ojob
  - common
  - SQL
  - SSH
  - SVN
  - Test
  - Debug
  - HBS
  - Basics
  - Rest
bugs:
  url: 'https://github.com/OpenAF/oJob-common/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-common
main: ''
mainJob: ''
license: Apache 2.0
version: '20171106'
dependencies:
  openaf: '>=20170309'
files:
  - .package.yaml
  - LICENSE
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobHBS.yaml
  - oJobOPack.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobSVN.yaml
  - oJobTest.yaml
  - README.md
filesHash:
  LICENSE: ff426822972c8972e3e4e782baac6f5304fd458c
  oJobBasics.yaml: d94c9f5e4df71100110d314f63e4944eea7652ad
  oJobDebug.yaml: 32c8c37b82cb9741cb34ffc1118b5df4498a63d7
  oJobHBS.yaml: b50587d772e2300cb3a0fd780a827601c8124e88
  oJobOPack.yaml: 288d5fe3efe667c4c6b6ff6e4440af86ee935490
  oJobRest.yaml: 69de46a614d8382b3702aa0ee8ec484b36bc2e3c
  oJobs.yaml: 26b881af6d2a0c36e26e3d428781cdde54e4ae23
  oJobSQL.yaml: 0974b81f2b253b9c68897d611820e5b60b632a18
  oJobSSH.yaml: 1dce0acada74ca40d61df40ec37f2e62a2d39c25
  oJobSVN.yaml: bf6942c5e78ff1a3b6422fdcb6d3f0a7796ed467
  oJobTest.yaml: 41d3a2e5865537c6040ede6ca78eb5bb063350dc
  README.md: de73d008f4e91bdd79afa859a00f6a3484129cb0
