author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: 'https://github.com/nmaguiar/oJob-common'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/nmaguiar/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
mainJob: ''
license: Apache 2.0
version: '20170411'
dependencies:
  openaf: '>=20170309'
files:
  - oJobBasics.yaml
  - LICENSE
  - oJobRest.yaml
  - oJobSVN.yaml
  - oJobHBS.yaml
  - oJobDebug.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - .package.yaml
  - README.md
  - oJobTest.yaml
  - oJobSSH.yaml
filesHash:
  oJobBasics.yaml: e67a906655a4bf1b315de07360f8449449efd187
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  oJobRest.yaml: e1a5f8d1809fffe51c285179f377f76300399eb0
  oJobSVN.yaml: c6dd797079a5fe01bfd92dbe4682ac0ebfb115c4
  oJobHBS.yaml: e45febb3c8f9b90ce0ac11a01411e7940e5c25f1
  oJobDebug.yaml: e48ee42df640aba62925d513aad6a4831d924cd9
  oJobs.yaml: b6fa547806a46b5551cc96b06f2d6ff63ba1f16c
  oJobSQL.yaml: e491518238ffddb798fdad756dbdfafd2495d8f0
  .package.yaml: f5bd80cae0755a5d26cbd5fc251a039184280b8e
  README.md: 626497dd1e492c621be6fa973a56373290708a2b
  oJobTest.yaml: 042a099074a433b41a169ddd105c5aebd11c9848
  oJobSSH.yaml: 61927c6d08212c187fe60f78555b2b14c7b9cd72
