author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: URL to track bugs
repository:
  type: http
  url: URL
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
license: Apache 2.0
version: '20170308'
dependencies:
  openaf: '>=20170309'
files:
  - oJobs.yaml
  - oJobBasics.yaml
  - oJobSSH.yaml
  - oJobDebug.yaml
  - LICENSE
  - .package.yaml
  - oJobTest.yaml
  - README.md
filesHash:
  oJobs.yaml: e72fe1e34a54175faf812c8dccd4d8a58efba93b
  oJobBasics.yaml: 1addaeb99679f8b63f0a1236752bfbb3d033e64e
  oJobSSH.yaml: cdbac9ce27352824a91a6a18ed5b4b01701d51ea
  oJobDebug.yaml: fd432680ca91620fb2e0d584f30bd6b3e78d1ae8
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  .package.yaml: fc773a05b5b18e9a587bbf5c3534347d82219466
  oJobTest.yaml: 18c82b63e9c80d35d5c10be9b6123d3142e34a44
  README.md: 626497dd1e492c621be6fa973a56373290708a2b
