author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - ojob
  - common
  - SQL
  - SSH
  - SVN
  - Test
  - Debug
  - HBS
  - Basics
  - Rest
  - ES
  - ElasticSearch
bugs:
  url: 'https://github.com/OpenAF/oJob-common/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-common
main: ''
mainJob: ''
license: Apache 2.0
version: '20180418'
dependencies:
  openaf: '>=20171101'
files:
  - .package.yaml
  - LICENSE
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobES.yaml
  - oJobHBS.yaml
  - oJobOPack.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobSVN.yaml
  - oJobTest.yaml
  - README.md
filesHash:
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  oJobBasics.yaml: e67a906655a4bf1b315de07360f8449449efd187
  oJobDebug.yaml: e48ee42df640aba62925d513aad6a4831d924cd9
  oJobES.yaml: fee36bc643eea9eb3b070d747755eab1f7ffc23f
  oJobHBS.yaml: ca018d16fcbdf3a9fc7450cab0d0325eed5e127f
  oJobOPack.yaml: d7ce712ee0a226a61330fdacfac6d043c28b66cf
  oJobRest.yaml: 2e8a03188e88b2ed5e52f8c575fd66006bb23122
  oJobs.yaml: 1331cb43b4808bfd47621eb0cf9e626f6986ceec
  oJobSQL.yaml: e491518238ffddb798fdad756dbdfafd2495d8f0
  oJobSSH.yaml: 61927c6d08212c187fe60f78555b2b14c7b9cd72
  oJobSVN.yaml: a6809d7993087b0fbe53e4e03678910db52b5fb3
  oJobTest.yaml: 9efaecac15234ef65b22d25a8fc990cd678e4470
  README.md: 626497dd1e492c621be6fa973a56373290708a2b
