author: nmaguiar@gmail.com
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
bugs:
  url: 'https://github.com/nmaguiar/oJob-common'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/nmaguiar/oJob-common/master'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-commons
main: ''
mainJob: ''
license: Apache 2.0
version: '20170811'
dependencies:
  openaf: '>=20170309'
files:
  - oJobBasics.yaml
  - oJobRest.yaml
  - oJobSVN.yaml
  - oJobHBS.yaml
  - oJobDebug.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - .package.yaml
  - oJobTest.yaml
  - oJobSSH.yaml
filesHash:
  oJobBasics.yaml: e67a906655a4bf1b315de07360f8449449efd187
  oJobRest.yaml: e1a5f8d1809fffe51c285179f377f76300399eb0
  oJobSVN.yaml: c6dd797079a5fe01bfd92dbe4682ac0ebfb115c4
  oJobHBS.yaml: e45febb3c8f9b90ce0ac11a01411e7940e5c25f1
  oJobDebug.yaml: e48ee42df640aba62925d513aad6a4831d924cd9
  oJobs.yaml: b6fa547806a46b5551cc96b06f2d6ff63ba1f16c
  oJobSQL.yaml: e491518238ffddb798fdad756dbdfafd2495d8f0
  .package.yaml: fd15018a13b3e2b0f8c1a8def5053fab5cc39be0
  oJobTest.yaml: d5b337d1c634d6c791563d94cde92a02cbcff5e8
  oJobSSH.yaml: 61927c6d08212c187fe60f78555b2b14c7b9cd72
