author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - ojob
  - common
  - SQL
  - SSH
  - SVN
  - Test
  - Net
  - Debug
  - HBS
  - Basics
  - HTTPd
  - Rest
  - ES
  - ElasticSearch
  - WatchDog
  - Email
bugs:
  url: 'https://github.com/OpenAF/oJob-common/issues'
repository:
  type: http
  backurl: 'https://raw.githubusercontent.com/OpenAF/oJob-common/master'
  url: 'https://openaf.io/opacks/oJob-common.opack'
description: A set of base oJobs as common building blocks for custom oJobs.
name: oJob-common
main: ''
mainJob: ''
license: Apache 2.0
version: '20181221'
dependencies:
  openaf: '>=20180527'
files:
  - .package.yaml
  - LICENSE
  - oJobBasics.yaml
  - oJobDebug.yaml
  - oJobES.yaml
  - oJobHBS.yaml
  - oJobHTTPd.yaml
  - oJobNet.yaml
  - oJobOPack.yaml
  - oJobRAID.yaml
  - oJobRest.yaml
  - oJobs.yaml
  - oJobSQL.yaml
  - oJobSSH.yaml
  - oJobSVN.yaml
  - oJobTest.yaml
  - oJobWatchDog.yaml
  - README.md
filesHash:
  LICENSE: 92170cdc034b2ff819323ff670d3b7266c8bffcd
  oJobBasics.yaml: 4cc8f05fbf58dfca3afcf56e003be67154831cbd
  oJobDebug.yaml: 556cf30c9b6108fe9e9228a470a43039b7550a1c
  oJobES.yaml: 0d5e7ba5181f3344490aab6c42466c9189986812
  oJobHBS.yaml: f314f109494e64e5ef5b24483a96ec59d54d6c11
  oJobHTTPd.yaml: 78952d4d61fccee86c5b6442436207a70f42cdc9
  oJobNet.yaml: a744fb83a9430ca9e34356bede5b0df8f2d48367
  oJobOPack.yaml: cd9542c6720f38758af1512060be295a8e608184
  oJobRAID.yaml: b4916cff81119a9e626c735abd6426964cdfc17c
  oJobRest.yaml: 495cd46622acddccf5b82d08d76a663bb7501ac0
  oJobs.yaml: 43db984437d36414f426075a31f5a3a0d1502432
  oJobSQL.yaml: e9adfe77c95fc0cf35478c23f5b21bc09dd63e57
  oJobSSH.yaml: c4270459c52d876181a74ee843ab99bed1c34fd7
  oJobSVN.yaml: ecfed00a4fa11b50ebf601168ac1251f7de29bfa
  oJobTest.yaml: 684560356b6e60c85c7230dd90c69c78fdd649f5
  oJobWatchDog.yaml: 3774f4bae284b0b14000a649ea0312efe610cbef
  README.md: 3248baaf4d65fd9833dc991201dd5c4bb0b24425
