# Define the jobs
# Author: Nuno Aguiar

jobs:
  ## ----------------------
  ## oJob Start/Stop basics
  ## ----------------------

  # Start processing
  - name        : oJob Start
    exec        : >
      log("init");
    
  # Stop processing on shutdown
  - name        : oJob Shutdown
    deps        :
       - oJob Start
    type        : shutdown
    exec        : >
      log("done");

  # Stop processing
  - name        : oJob Stop
    deps        :
       - oJob Start
    exec        : >
      log("done");

  # Exit the current script (include openaf-console)
  - name        : oJob Exit
    exec        : exit(0);

  ## -----
  ## Utils
  ## -----
  
  # Sleep for 5 seconds
  - name        : oJob Sleep 5s
    exec        : sleep(5000); 
 
  # Sleep for 1 second
  - name        : oJob Sleep 1s
    exec        : sleep(1000);
    
  ## ------------
  ## Send email
  ## ------------
  
  - name       : oJob Send email
    help       : |
      This jobs tries to send an email. Expects:
        - args.server         (String)  The email server to use
        - args.port           (Number)  The email server port to use
        - args.from           (String)  The email from address
        - args.to             (Array)   The email to addresses
        - args.cc             (Array)   The email cc addresses
        - args.bcc            (Array)   The email bcc addresses
        - args.isHTML         (Boolean) Specifies if the email is in HTML format
        - args.output         (String)  The email body message (a hbs template using args as data)
        - args.altOutput      (String)  The email body alternative message (defaults to message)
        - args.credentials    (Map)     The email server credentials (user and pass)
        - args.useSSL         (Boolean) If the email server uses SSL
        - args.useTLS         (Boolean) If the email server uses TLS
        - args.embedFiles     (Array)   Array of maps (with file and name) to embeded on the email
        - args.addAttachments (Array)   Array of maps (with file, isInLine, name) to attach on the email
        - args.addImages      (Array)   Array of urls to images (only available if isHTML = true)
        - args.embedURLs      (Array)   Array of maps (with url and name) to embeded on the email
        - args.subject        (String)  The email subject (a hbs template using args as data)
        - args.debug          (Boolean) Determines if it should debug the process
    exec       : |
      _$(args.server).isString().$_("Please provide an email server.");
      _$(args.from).isString().$_("Please provide a from email address.");
      _$(args.to).isArray().$_("Please provide the to email addresses.");
      _$(args.subject).isString().$_("Please provide a subject.");
      _$(args.output).isString().$_("Please provide an output.");
      args.cc          = _$(args.cc).isArray().default([]);
      args.bcc         = _$(args.bcc).isArray().default([]);
      args.debug       = _$(args.debug).isBoolean().default(void 0);
      args.port        = _$(args.port).isNumber().default(void 0);
      args.useSSL      = _$(args.useSSL).isBoolean().default(true);
      args.useTLS      = _$(args.useTLS).isBoolean().default(false);
      args.embedFiles  = _$(args.embedFiles).isArray().default(void 0);
      args.embedURLs   = _$(args.embedURLs).isArray().default(void 0);
      args.addImages   = _$(args.addImages).isArray().default(void 0);
      args.isHTML      = _$(args.isHTML).isBoolean().default(false);
      args.altOutput   = _$(args.altOutput).isString().default(args.output);
      args.credentials = _$(args.credentials).isMap().default(void 0);

      plugin("Email");
      var email = new Email(args.server, args.from, args.useSSL, args.useTLS, args.isHTML);
      if (isDef(args.port)) email.setPort(args.port);
      email.setCharset("UTF-8");

      if (isDef(args.credentials)) email.setCredentials(args.credentials.user, args.credentials.pass);
      if (args.debug) email.getEmailObj().setDebug(true);

      if (isDef(args.embedFiles)) {
        for(var ii in args.embedFiles) {
          email.embedFile(embedFiles[ii].file, embedFiles[ii].name);
        };
      }

      if (isDef(args.embedURLs)) {
        for(var ii in args.embedURLs) {
          email.embedURL(embedURLs[ii].url, embedURLs[ii].name);
        };
      }

      if (isDef(args.addAttachments)) {
        for(var ii in args.addAttachments) {
          email.addAttachment(args.addAttachments[ii].file, args.addAttachments[ii].isInLine, void 0, args.addAttachments[ii].name);
        };
      }

      if (isDef(args.addImages)) {
        for(var ii in args.addImages) {
          email.addExternalImage(args.addImages[ii]);
        };
      }

      if (args.isHTML) {
        email.setHTML(templify(args.output, args));
      } else {
        email.setMessage(templify(args.output, args));
      }
      
      try {
      args.result = email.send(templify(args.subject, args), templify(args.altOutput, args), args.to, args.cc, args.bcc, args.from);
      } catch(e) {
        e.javaException.printStackTrace();
      }

  ## ------------
  ## oJob shell
  ## ------------
  
  # Run a shell command
  - name        : oJob sh
    help        : |
      This job runs a local shell command and accepts the following args:
        - args.cmd       (string)  The command to execute (or an array of commands)
        - args.quiet     (boolean) Determines if the stdout should be visible or not (default is false)
        - args.directory (string)  Sets the working directory for the command
        - args.stdin     (string)  Provide any stdin needed
        - args.exitcode  (number)  Determines what exitcode should be consider success (default is 0)
        - args.stderr    (string)  Get's set to the stderr
        - args.stdout    (string)  Get's set to the stdout 
        
    exec        : |
      if (isUnDef(args.stdin)) args.stdin = true;
      if (isUnDef(args.exitcode)) args.exitcode = 0;
      if (isArray(args.cmd)) {
        args.stdout = "";
        args.stderr = "";
        for(var i in args.cmd) {
          var res = sh(args.cmd[i], args.stdin, args.timeout, !args.quiet, args.directory, true);
          args.stdout += res.stdout
          args.stderr += res.stderr;
          if (res.exitcode != args.exitcode) throw "Exit code (for command '" + args.cmd[i] + "'): " + res.exitcode;
        }
      } else {
        var res = sh(args.cmd, args.stdin, args.timeout, !args.quiet, args.directory, true);
        args.stdout = res.stdout;
        args.stderr = res.stderr;
        if (res.exitcode != args.exitcode) throw "Exit code: " + res.exitcode;
      }

  ## ------------
  ## oJob Logging
  ## ------------
  
  # Display oJob Log
  - name        : oJob Show Log
    exec        : >
      log(stringify(
        (isUnDef(args.name) ? 
         ow.oJob.getLogCh().getAll() 
         : 
         $from(ow.oJob.getLogCh().getAll()).equals("name", args.name).select()
        )
      ));
