# Define the jobs
#
jobs:
  ## -----------------
  ## SSH functionality
  ## -----------------

  # Exec commands over SSH
  - name        : SSH Exec
    help        : >
      Executes commands on a SSH connection. The expected arguments are:
        - args.cmd      (String)   A SSH command-line to execute
        - args.stdin    (String)   An optional SSH stdin for the command-line to execute
        - args.chHosts  (Channel)  A channel with hosts configurations to use instead of individual config
        - args.host     (String)   The SSH host
        - args.port     (Number)   The SSH port (defaults to 22)
        - args.login    (String)   The SSH login
        - args.pass     (String)   The SSH pass
        - args.key      (String)   The path to a SSH key file
    exec        : >
      plugin("SSH");
      if (isDef(args.chHosts)) {
         $from($ch(args.chHosts).getAll()).select(function(r) {
            if (isUnDef(r.port)) r.port = 22;
            if (isUnDef(r.stdin)) r.stdin = "";

            var s = new SSH(r.host, r.port, r.login, r.pass, r.key, true);
            log("[" + r.host + ":" + r.port + "]\n" + s.exec(args.cmd, args.stdin));
            s.close();
         })
      } else {
        if (isUnDef(args.port)) args.port = 22;
        if (isUnDef(args.stdin)) args.stdin = "";

        var s = new SSH(args.host, args.port, args.login, args.pass, args.key, true);
        log("[" + args.host + ":" + args.port + "]\n" + s.exec(args.cmd, args.stdin));
        s.close();
      }

  # Copies files over SSH
  - name        : SSH Send
    help        : >
      Executes commands on a SSH connection. The expected arguments are:
        - args.source   (String)   The source file to copy 
        - args.target   (String)   The target filepath 
        - args.chHosts  (Channel)  A channel with hosts configurations to use instead of individual config
        - args.host     (String)   The SSH host
        - args.port     (Number)   The SSH port (defaults to 22)
        - args.login    (String)   The SSH login
        - args.pass     (String)   The SSH pass
        - args.key      (String)   The path to a SSH key file
    exec        : >
      plugin("SSH");
      if (isDef(args.chHosts)) {
         $from($ch(args.chHosts).getAll()).select(function(r) {
            if (isUnDef(r.port)) r.port = 22;

            var s = new SSH(r.host, r.port, r.login, r.pass, r.key, true);
            log("[" + r.host + ":" + r.port + "] Copying " + args.source + " to " + args.target);
            s.put(args.source, args.target);
            s.close();
         })
      } else {
        if (isUnDef(args.port)) args.port = 22;

        var s = new SSH(args.host, args.port, args.login, args.pass, args.key, true);
        log("[" + args.host + ":" + args.port + "] Copying " + args.source + " to " + args.target);
        s.put(args.source, args.target);
        s.close();
      }
