# oPack oJob functionality
# Author: Nuno Aguiar

jobs:
   # oPack Pack external
   #
   - name: oPack Pack external
     help: > 
        Packs an external opack given an url or opack name:
         
          name        (String)  The url or opack name to pack
          tmpDir      (String)  Temporary folder to use (defaults to "./tmp")
          outputDir   (String)  Output folder where the opack will be placed (defaults to ".")
     exec: >
       if (isUnDef(args.tmpDir))    args.tmpDir    = "./tmp";
       if (isUnDef(args.outputDir)) args.outputDir = ".";
       if (isUnDef(args.name))      throw "You need to define a opack args.name.";

       if (getVersion() < 20171106) logWarn("It's advisable to use an OpenAF version equal or greater than 20171106.");

       io.rm(args.tmpDir);
       io.mkdir(args.tmpDir);
       io.mkdir(args.outputDir);

       sync(() => {
          oPack("install " + args.name + " -d " + args.tmpDir + " -justcopy");
          oPack("pack " + args.tmpDir);
       }, oPack);

       var pack;
       try {
          pack = io.readFile(args.tmpDir + "/.package.json");
       } catch(e) {
          pack = io.readFileYAML(args.tmpDir + "/.package.yaml");
       }

       io.mv(pack.name + "-" + pack.version + ".opack", args.outputDir + "/" + pack.name + "-" + pack.version + ".opack");
       for(var file in pack.files) {
         io.rm(args.tmpDir + "/" + pack.files[file]);
       }
       io.rm(args.tmpDir);
