# Test oJob functionality
# Author: nmaguiar@gmail.com

jobs:
 # Test assert
 #
 - name: oJob Assert
   help: >
     This job will assert that args.a and args.b provided are equal. Otherwise it will 
     display the args.msg message.
   exec: >
     if(isUnDef(args.a) || isUnDef(args.b)) throw "Please define args.a and args.b.";
     if(isUnDef(args.msg)) args.msg = "A is different from B";

     ow.loadTest().assert(args.a, args.b, args.msg); 

 # Test functions
 #
 - name: oJob Test
   help: >
     This job will test a args.func (function) provided. The test will use the current
     oJob job name.
   exec: >
     if (isUnDef(args.func)) throw "Please define args.func.";
     if (!(isFunction(args.func))) args.func = new Function(args.func);
     ow.loadTest().test(job.name, args.func);   

 # test outside commands
 #
 - name: oJob Test sh
   help: >
     This job will test a args.cmd (shell command) provided. The test will use the current
     oJob job name.
   exec: >
     if (isUnDef(args.cmd)) throw "Please define args.cmd.";
     ow.loadTest().test(job.name, args.cmd); 

 # Test results jobs
 #

 - name: oJob Test Results
   help: |
     Prints or outputs (if args.quite = true) a args.results with: count of tests, tests passed, tests failed and all profile information.
   exec: >
     args.results = {
        count: ow.loadTest().getCountTest(),
        pass: ow.loadTest().getCountPass(),
        fail: ow.loadTest().getCountFail(),
        profile: ow.loadTest().__profile
     };
     if ((isDef(args.quite) && !args.quite) || isUnDef(args.quite)) print(af.toYAML(args.results));

 - name: oJob Test Todo results
   help: |
     Prints or outputs (if args.quite = true) a args.results with: count of tests, tests passed and tests failed.
   exec: >
     args.results = {
        count: $ch("oJob::logs").size(),
        pass: $from($ch("oJob::logs").getAll()).equals("success", true).count(),
        fail: $from($ch("oJob::logs").getAll()).equals("error", true).count()
     };
     if ((isDef(args.quite) && !args.quite) || isUnDef(args.quite)) print(af.toYAML(args.results));

# JUnit results
#

 - name: oJob Generate JUnit XML
   help: >
     This job will generate a JUnit XML with the current test results. You can provide:
       - suitesId    (String)   The JUnit suites id 
       - suitesName  (String)   The JUnit suites name
       - resultsFile (String)   The filename and path where to store the JUnit results.
   exec: |
     if (isUnDef(args.suitesId)) args.suitesId = "test";
     if (isUnDef(args.suitesName)) args.suitesName = "test";
     if (isUnDef(args.resultsFile)) args.resultsFile = "testResults.xml";
     io.writeFileString(args.resultsFile, ow.loadTest().toJUnitXML(args.suitesId, args.suitesName)); 