# Template oJob functionality
# Author: nmaguiar@gmail.com

jobs:
 # oJob HBS file 
 #
 - name: oJob HBS file
   help: >
     This job will apply an args.template hbs file using args.data to produce a new
     file (args.target). 
   exec: >
     if(isUnDef(args.template)) throw "Need to define a args.template filename to use";
     if(isUnDef(args.target)) throw "Need to define a args.target filename to write the output to";

     io.writeFileString(args.target, ow.loadTemplate().parseHBS(args.template, args.data)); 
     if (isUnDef(args.quiet) || !args.quiet) log("Wrote '" + args.target + "'' based on '" + args.template + "'");

 # oJob HBS
 #
 - name: oJob HBS
   help: >
     This job will apply an args.tempalte hbs file using args.data to produce contents to args.output.
   exec: >
     if(isUnDef(args.template)) throw "Need to define a args.template filename to use";

     args.output = ow.loadTemplate().parseHBS(args.template, args.data); 
