# Copyright 2025 Nuno Aguiar
# MCP Server Job
# This job starts a MCP server that listens for requests and executes jobs based on the requests.

include:
- oJobHTTPd.yaml

jobs:
# -------------------------
- name    : HTTP MCP Server
  typeArgs:
    noLog   : false 
    shortcut:
      name  : httpdMCP
      keyArg: port
      args  :
        description: description
        uri        : uri
        debug      : debug
        fnsMeta    : fnsMeta
        fns        : fns
  help    :
    text: Starts a MCP server to handle requests with execution of jobs.
    expects: 
    - name: port 
      desc: (Number) The port to listen on.
    - name: uri
      desc: (String) The URI to handle requests. Default is "/mcp".
    - name: debug
      desc: (Boolean) If true, debug messages will be logged.
    - name: fnsMeta
      desc: (Array) Metadata for the functions available in the MCP server.
    - name: fns
      desc: (Map) Functions to be executed when called from the MCP server.
  check   :
    in: 
      description: isMap.default(__)
      port       : isNumber
      uri        : isString.default("/mcp")
      debug      : isBoolean.default(false)
      fnsMeta    : isArray.default([])
      fns        : isMap.default({})
  deps    :
  - HTTP Start Server
  exec    : | #js
    // Ensures default server info and capabilities
    args.description = merge({
      serverInfo: {
          name: "OpenAF",
          title: "OpenAF MCP server",
          version: "1.0.0"
      },
      capabilities: {
          prompts: {
              listChanged: true
          },
          tools: {
              listChanged: true
          }
      }
    }, args.description)

    fns = {}
    fns[args.uri] = req => ow.server.httpd.replyJSONRPC(global.__ojobHttp[args.port], req, {
        initialize                 : params => {
            if (args.debug) log(`initialize -- ${af.toCSLON(params)}`)
            return args.description
        },
        "notifications/initialized": params => ({}),
        "tools/call"               : params => {
            if (args.debug) log(`tools/call -- ${af.toCSLON(params)}`)
            var _res
            if (isDef(args.fns[params.name])) {
              try {
                if (isString(args.fns[params.name])) {
                  _res = $job(args.fns[params.name], params.arguments)
                  if (isMap(_res)) {
                    delete _res.objId
                    delete _res.execid
                  }
                } else {
                  throw "Function not found: " + params.name
                }
              } catch(e) {
                logErr(`Error executing tool '${params.name}': ${e.message}`)
                _res = {
                    content: [{
                        type: "text",
                        text: `Error executing tool '${params.name}': ${e.message}`
                    }],
                    isError: true
                }
                $err(e)
              }
            } else {
              _res = {
                  content: [{
                      type: "text",
                      text: `Error: Unknown tool '${params.name}'`
                  }],
                  isError: true
              }
            }
            if (isString(_res.text)) {
              _res = {
                  content: [{
                      type: "text",
                      text: _res.text
                  }],
                  isError: false
              }
            } else if (isUnDef(_res.result)) {
              _res = {
                  content: [{
                      type: "text",
                      text: stringify(_res, __, "")
                  }],
                  isError: false
              }
            } else {
              _res = _res.result
            }

            if (args.debug) log(`tools/call -- response: ${af.toCSLON(_res)}`)
            return _res
        },
        "tools/list": params => {
            if (args.debug) log(`tools/list -- ${af.toCSLON(params)}`)
            args.fnsMeta = Object.keys(args.fns).map(f => {
              if (isDef(args.fnsMeta[f])) {
                return args.fnsMeta[f]
              } else {
                return {
                  name       : f,
                  description: f,
                  inputSchema: {}
                }
              }
            })
            return {
                tools: args.fnsMeta
            }
        },
        "prompts/list": params => ({})
    }, log, logWarn)

    ow.server.httpd.route(global.__ojobHttp[args.port], merge(global.__ojobRoutes[args.port], fns))
    log("READY [" + args.port + "]")

# --------------------------
- name    : STDIO MCP Server
  typeArgs:
    noLog   : false 
    shortcut:
      name  : stdioMCP
      keyArg: description
      args  :
        debug      : debug
        fnsMeta    : fnsMeta
        fns        : fns
  help    :
    text: Starts a MCP stdio to handle requests with execution of jobs.
    expects: 
    - name: debug
      desc: (String) If defined it will create a ndjson file with the provided name.
    - name: fnsMeta
      desc: (Array) Metadata for the functions available in the MCP server stdio.
    - name: fns
      desc: (Map) Functions to be executed when called from the MCP server stdio.
  check   :
    in: 
      description: isMap.default(__)
      debug      : isString.default(__)
      fnsMeta    : isArray.default([])
      fns        : isMap.default({})
  exec    : | #js
    // Ensures default server info and capabilities
    args.description = merge({
      serverInfo: {
          name: "OpenAF",
          title: "OpenAF server",
          version: "1.0.0"
      },
      capabilities: {
          prompts: {
              listChanged: true
          },
          tools: {
              listChanged: true
          }
      }
    }, args.description)

    var fs = {}
    Object.keys(args.fns).map(f => {
      fs[f] = function(params) {
        var _r = $job(args.fns[f], params)
        if (isMap(_r)) {
          delete _r.objId
          delete _r.execid
        }
        return _r
      }
    })

    ow.server.mcpStdio(args.description, args.fnsMeta, 
      fs,
      (type, msg) => {
      if (args.debug) {
        io.writeLineNDJSON(args.debug, { type: type, msg: msg })
      }
    })


# - name: ping
#   exec: | #js
#     args.text = "PONG!"

# - name: echo
#   exec: | #js
#     args.text = args.text

# - name: specialSum
#   exec: | #js
#     args.text = Number(args.a) + Number(args.b) * 2

# ojob:
#   #logToConsole: false
#   daemon      : true

# todo:
# #- (stdioMCP ): {}
# #  ((debug  )): /Applications/OpenAF/oJob-common/log.ndjson
# - (httpdStart): 17878
# - (httpdMCP  ): 17878
#   ((debug   )): true
#   ((uri     )): "/mcp"
#   ((fnsMeta)):
#   - name       : ping
#     description: Pings the server
#     inputSchema:
#       type: object
#       properties:
#         text:
#           type: string
#           description: Text to return
#       required: ["text"]
#     annotations:
#       title       : Ping
#       readOnlyHint: false
#       idempotentHint: true
#   - name       : echo
#     description: Echoes the input
#     title      : echo
#     inputSchema: 
#       type: object
#       properties:
#         text:
#           type: string
#           description: Text to echo
#       required: ["text"]
#     annotations:
#       title       : Echo
#       readOnlyHint: false
#       idempotentHint: true
#   - name       : specialSum
#     description: Performs a special sum
#     inputSchema:
#       type: object
#       properties:
#         a:
#           type: number
#           description: the a number of the sum
#         b:
#           type: number
#           description: the b number of the sum
#       required: ["a","b"]
#     annotations:
#       title: specialSum
#       readOnlyHint: false
#   ((fns    )):
#     ping: ping
#     echo: echo
#     specialSum: specialSum
