# Name your includes
#
include:
  - hello.js   # Some nice hello function
  - jobs/basics.yaml  # Include basic jobs
  - jobs/debug.yaml
  - jobs/ssh.yaml

# Define the jobs
#
jobs:
  # Hello world after start processing
  - name	      : Hello world
    deps        : 
      - oJob Start
    exec 	      : |
      hello(args.name);

  # Bye world
  - name        : Bye
    deps        :
      - SSH Check uptime 
    exec        :
      print("bye, nice to meet you.");

  # Say the time regularly
  - name        : Say the time
    type        : periodic
    typeArgs    :
      timeInterval   : 1000
      waitForFinish  : true
      cron           : "*/5 * * * * *"
    exec        : |
      print(new Date());

  - name        : Load hosts channel
    deps        :
      - oJob Start
    exec        :
      $ch("hosts").create().setAll(["host"], io.readFileYAML(args.file));

  - name        : SSH Check uptime
    from        : SSH Exec
    deps        :
      - Load hosts channel

  - name        : SSH Send OpenAF
    to          : SSH Send
    deps        :
      - Load hosts channel
    exec        : |
      args.source = "&OpenAF/openaf.jar"
      args.target = "openaf.jar"

# List what to do 
#
todo:
  - oJob Log
  - oJob Start
  - name: Load hosts channel
    args:
      file: chServers.yaml
  - name: SSH Check uptime
    args: 
      chHosts: hosts
      cmd    : uptime; df -h
  - name: SSH Send OpenAF
    args:
      chHosts: hosts
  #- Say the time
  #- name : Hello world
  #  args : 
  #    name: Nuno
  #- Bye
  - Bye

# This will be a daemon
# 
ojob:
  daemon: false
  unique:
    pidFile     : helloworld.pid
    killPrevious: true
  channels:
    expose     : true
    port       : 17878
    permissions: r
    #list       :
    #  - __oJob::log
    #auth       :
    #  - login: ojob
    #    pass : ojob
    #    permissions: r